export interface IEdition {
    id?: string,
    year: string,
    theme: string,
    edition_name: string,
    initial_registration_date: string,
    final_registration_date: string,
    initial_submission_date: string,
    final_submission_date: string,
    initial_advisor_date: string,
    final_advisor_date: string,
    initial_registration_evaluators_date: string,
    final_registration_evaluators_date: string,
    initial_evaluators_date: string,
    final_evaluators_date: string,
    workload: string,
    banner: string | null,
    logo: string | null,
    is_open: boolean,
}
