/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutIntrodution: typeof import('./components/AboutIntrodution.vue')['default']
    AboutProgramation: typeof import('./components/AboutProgramation.vue')['default']
    BtnPrimary: typeof import('./components/BtnPrimary.vue')['default']
    EditionsView: typeof import('./components/EditionsView.vue')['default']
    EvaluationSection: typeof import('./components/EvaluationSection.vue')['default']
    FooterComp: typeof import('./components/FooterComp.vue')['default']
    FooterComp2: typeof import('./components/FooterComp2.vue')['default']
    IssuesPreview: typeof import('./components/IssuesPreview.vue')['default']
    LayoutDashboard: typeof import('./components/LayoutDashboard.vue')['default']
    LayoutDefault: typeof import('./components/LayoutDefault.vue')['default']
    MainBanner: typeof import('./components/MainBanner.vue')['default']
    PersonTable: typeof import('./components/PersonTable.vue')['default']
    RangeComponent: typeof import('./components/rangeComponent.vue')['default']
    RecivedTable: typeof import('./components/RecivedTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleH1: typeof import('./components/TitleH1.vue')['default']
  }
}
