/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutBanner: typeof import('./components/AboutBanner.vue')['default']
    AboutIntrodution: typeof import('./components/AboutIntrodution.vue')['default']
    AboutProgramation: typeof import('./components/AboutProgramation.vue')['default']
    AddUserGroup: typeof import('./components/auth/AddUserGroup.vue')['default']
    BackButton: typeof import('./components/globals/buttons/BackButton.vue')['default']
    BtnPrimary: typeof import('./components/globals/buttons/BtnPrimary.vue')['default']
    CardUser: typeof import('./components/steps/layout/CardUser.vue')['default']
    CreateGroup: typeof import('./components/auth/CreateGroup.vue')['default']
    EditionDatas: typeof import('./components/EditionDatas.vue')['default']
    EditionsView: typeof import('./components/EditionsView.vue')['default']
    EvaluationSection: typeof import('./components/EvaluationSection.vue')['default']
    FinalStep: typeof import('./components/steps/stepbystep/FinalStep.vue')['default']
    FooterComp: typeof import('./components/FooterComp.vue')['default']
    FooterComp2: typeof import('./components/FooterComp2.vue')['default']
    InformativeAlert: typeof import('./components/InformativeAlert.vue')['default']
    IsDev: typeof import('./components/IsDev.vue')['default']
    IssuesPreview: typeof import('./components/IssuesPreview.vue')['default']
    LayoutDashboard: typeof import('./components/LayoutDashboard.vue')['default']
    LayoutDefault: typeof import('./components/LayoutDefault.vue')['default']
    LayoutPanel: typeof import('./components/LayoutPanel.vue')['default']
    LayoutSteps: typeof import('./components/LayoutSteps.vue')['default']
    MainBanner: typeof import('./components/MainBanner.vue')['default']
    MyThemes: typeof import('./components/MyThemes.vue')['default']
    PaperAcceptanceTable: typeof import('./components/PaperAcceptanceTable.vue')['default']
    PersonTable: typeof import('./components/PersonTable.vue')['default']
    RangeComponent: typeof import('./components/rangeComponent.vue')['default']
    RecivedTable: typeof import('./components/RecivedTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepbyStepHeader: typeof import('./components/steps/layout/StepbyStepHeader.vue')['default']
    StepContainer: typeof import('./components/inputs/StepContainer.vue')['default']
    StepDialog: typeof import('./components/steps/layout/StepDialog.vue')['default']
    StepFive: typeof import('./components/steps/stepbystep/StepFive.vue')['default']
    StepFour: typeof import('./components/steps/stepbystep/StepFour.vue')['default']
    StepOne: typeof import('./components/steps/stepbystep/StepOne.vue')['default']
    StepsAction: typeof import('./components/steps/layout/StepsAction.vue')['default']
    StepsHeader: typeof import('./components/steps/layout/StepsHeader.vue')['default']
    StepThree: typeof import('./components/steps/stepbystep/StepThree.vue')['default']
    StepTwo: typeof import('./components/steps/stepbystep/StepTwo.vue')['default']
    SubjectChips: typeof import('./components/steps/SubjectChips.vue')['default']
    SuccessStep: typeof import('./components/steps/layout/SuccessStep.vue')['default']
    TitleH1: typeof import('./components/TitleH1.vue')['default']
    UserList: typeof import('./components/auth/UserList.vue')['default']
    UserSelected: typeof import('./components/inputs/UserSelected.vue')['default']
  }
}
