/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/auth/get-password/': RouteRecordInfo<'/auth/get-password/', '/auth/get-password', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/reset-password/': RouteRecordInfo<'/auth/reset-password/', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/token/': RouteRecordInfo<'/auth/token/', '/auth/token', Record<never, never>, Record<never, never>>,
    '/dashboard/colaborators/': RouteRecordInfo<'/dashboard/colaborators/', '/dashboard/colaborators', Record<never, never>, Record<never, never>>,
    '/dashboard/editions/': RouteRecordInfo<'/dashboard/editions/', '/dashboard/editions', Record<never, never>, Record<never, never>>,
    '/dashboard/editions/add/': RouteRecordInfo<'/dashboard/editions/add/', '/dashboard/editions/add', Record<never, never>, Record<never, never>>,
    '/dashboard/editions/all/': RouteRecordInfo<'/dashboard/editions/all/', '/dashboard/editions/all', Record<never, never>, Record<never, never>>,
    '/dashboard/editions/view/[id]': RouteRecordInfo<'/dashboard/editions/view/[id]', '/dashboard/editions/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/paper/[id]': RouteRecordInfo<'/dashboard/paper/[id]', '/dashboard/paper/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/register-evaluators/': RouteRecordInfo<'/dashboard/register-evaluators/', '/dashboard/register-evaluators', Record<never, never>, Record<never, never>>,
    '/editions/': RouteRecordInfo<'/editions/', '/editions', Record<never, never>, Record<never, never>>,
    '/editions/all/': RouteRecordInfo<'/editions/all/', '/editions/all', Record<never, never>, Record<never, never>>,
    '/editions/view/[id]': RouteRecordInfo<'/editions/view/[id]', '/editions/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/panel/': RouteRecordInfo<'/panel/', '/panel', Record<never, never>, Record<never, never>>,
    '/panel/paper/[id]': RouteRecordInfo<'/panel/paper/[id]', '/panel/paper/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/panel/registration-of-topics/': RouteRecordInfo<'/panel/registration-of-topics/', '/panel/registration-of-topics', Record<never, never>, Record<never, never>>,
    '/panel/work-submission/': RouteRecordInfo<'/panel/work-submission/', '/panel/work-submission', Record<never, never>, Record<never, never>>,
  }
}
